//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:{{MODULE}}_{{MASTER_SLAVE_BUS}}
//          _sequencer_config _driver_config _monitor_config 
//          _agent_config _ral_config
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
{%for i in range(0,3)%}
{%if i==0%} {%set name="sequencer"%}
{%elif i==1%}{%set name="driver"%}
{%elif i==2%}{%set name="monitor"%}
{%endif%}
class {{MASTER_SLAVE_BUS}}_{{name}}_config extends uvm_object;
	// Add user {{name}} cfg here
	
	// User {{name}} cfg ends
	`uvm_object_utils_begin({{MASTER_SLAVE_BUS}}_{{name}}_config)
	// Add user {{name}} cfg here
	//e.g. `uvm_field_int
	// User {{name}} cfg ends
	`uvm_object_utils_end
	function new(string name="{{MASTER_SLAVE_BUS}}_{{name}}_config");
		super.new(name);
	endfunction
endclass
{%endfor%}

class {{MASTER_SLAVE_BUS}}_agent_config extends uvm_object;
	{{MASTER_SLAVE_BUS}}_sequencer_config  sqr_cfg;
	{{MASTER_SLAVE_BUS}}_driver_config  drv_cfg;
	{{MASTER_SLAVE_BUS}}_monitor_config  moi_cfg;
	uvm_active_passive_enum is_active=UVM_ACTIVE;
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin({{MASTER_SLAVE_BUS}}_agent_config)
		`uvm_field_enum(uvm_active_passive_enum,is_active,UVM_ALL_ON)
		// Add user cfg here
		//e.g. `uvm_field_int
		// User cfg ends
	`uvm_object_utils_end
	function new(string name="{{MASTER_SLAVE_BUS}}_agent_config");
		super.new(name);
		sqr_cfg=new("sqr_cfg");
		drv_cfg=new("drv_cfg");
		moi_cfg=new("moi_cfg");
		// Add user cfg here
	
		// User new cfg ends
		{{new}}
	endfunction
	{{method}}
	// Add user method here
	//e.g. function
	// User method ends
endclass

{%if UVM_RAL%}
class {{MASTER_SLAVE_BUS}}_ral_config extends uvm_object;
	bit auto_prediction=1; //default auto perdict
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin({{MASTER_SLAVE_BUS}}_ral_config)
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_end
	function new(string name="{{MASTER_SLAVE_BUS}}_ral_config");
		super.new(name);
	endfunction
endclass
{%endif%}
