//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:{{MODULE}}_harness
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
module tb();

//instance interface
{%-for port in all_clk_rst-%} 
	reg {{port.bit_info}} {{port.name}};
{%-endfor-%});
{%for agt in agt_list%}
	{{MODULE}}_{{agt.name}}_inf   {{agt.name}}_inf;
{%endfor%}

//instance dut
{{dut_instance}}

initial begin
{%for agt in agt_list%}
	uvm_config_db#(virtual {{MODULE}}_{{agt.name}}_inf)::set(null,"uvm_test_top.env.{{agt.name}}_agt","{{agt.name}}_inf",{{agt.name}}_inf);
{%endfor%}
end

initial
begin
	`ifdef DUMP_FSDB
		$fsdbDumpfile("simv.fsdb");
		$fsdbDumpvars(0,tb);
	`endif
	`ifdef DUMP_VPD
		$vcdpluson();
	`endif
end

initial
begin
	$display("-------------------------------------------------------");
	$display("------------------------Start--------------------------");
	$display("-------------------------------------------------------");
	run_test();
	$display("-------------------------------------------------------");
	$display("-----------------------Finish--------------------------");
	$display("-------------------------------------------------------");
end

// Add user logic here

// User logic ends
endmodule