//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:{{MODULE}}_{{MASTER_SLAVE_BUS}}_monitor
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class {{MODULE}}_{{MASTER_SLAVE_BUS}}_monitor extends uvm_monitor ;

	`uvm_component_utils({{MODULE}}_{{MASTER_SLAVE_BUS}}_monitor)
	`uvm_register_cb({{MODULE}}_{{MASTER_SLAVE_BUS}}_monitor,{{MODULE}}_callback)

	//Config	//Interface
	{{MASTER_SLAVE_BUS}}_monitor_config moi_cfg;
	virtual {{MODULE}}_{{MASTER_SLAVE_BUS}}_inf {{MASTER_SLAVE_BUS}}_inf;
	
	//TLM 
	uvm_analysis_port#({{MASTER_SLAVE_BUS}}_req) moi_port;
	
	//Transaction Sequence item
	{{MASTER_SLAVE_BUS}}_req  moi_req;
	
	//Constructor Function
	function new(string name="{{MODULE}}_{{MASTER_SLAVE_BUS}}_monitor",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	
	//Phase Methods
	extern virtual function void build_phase(uvm_phase phase);
	extern virtual function void connect_phase(uvm_phase phase);
	extern virtual task run_phase(uvm_phase phase);
	
	//Task Function Methods
	extern task moi_request();
	
	{{method}}
	// Add user method here
	//e.g. task function
	// User method ends
endclass

function void {{MODULE}}_{{MASTER_SLAVE_BUS}}_monitor::build_phase(uvm_phase phase);
	super.build_phase(phase);
	`uvm_info(get_name(),"Build Phase is Called",UVM_LOW)
//	if(!uvm_config_db#({{MASTER_SLAVE_BUS}}_monitor_config)::get(this,"","moi_cfg",moi_cfg))
//	begin
//		`uvm_fatal(get_name(),"Failed Get {{MASTER_SLAVE_BUS}} Monitor Config")
//	end
	moi_port=new("moi_port",this);
	{{build_phase}}
	// Add user build here
	//e.g. TLM build
	// User build ends
endfunction

function void {{MODULE}}_{{MASTER_SLAVE_BUS}}_monitor::connect_phase(uvm_phase phase);
	super.connect_phase(phase);
	`uvm_info(get_name(),"Connect Phase is Called",UVM_LOW)
	{{connect_phase}}
	// Add user connect here
	//e.g. TLM  interface connect
	// User connect ends
endfunction

task {{MODULE}}_{{MASTER_SLAVE_BUS}}_monitor::run_phase(uvm_phase phase);
	super.run_phase(phase);
	`uvm_info(get_name(),"Run Phase is Called",UVM_LOW)
	fork
		moi_request();
	// Add user logic here

	// User logic ends
	{{run_phase_fork}}
	join
	// Add user logic here
	//e.g. task function `uvm_do_callbacks
	// User logic ends	
	{{run_phase_main}}
endtask

task {{MODULE}}_{{MASTER_SLAVE_BUS}}_monitor::moi_request();
	forever
	begin
		moi_req={{MASTER_SLAVE_BUS}}_req::type_id::create("moi_req",this);
		// Add user logic here
		#1;
		// User logic ends
		moi_port.write(moi_req);
	end
endtask
