//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:{{MODULE}}_{{MASTER_SLAVE_BUS}}_sequencer
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class {{MODULE}}_{{MASTER_SLAVE_BUS}}_sequencer extends uvm_sequencer 
{%-if response-%}#({{MASTER_SLAVE_BUS}}_req,{{MASTER_SLAVE_BUS}}_rsp);
{%-else-%}#({{MASTER_SLAVE_BUS}}_req);
{%endif%}
	`uvm_component_utils({{MODULE}}_{{MASTER_SLAVE_BUS}}_sequencer)
	//Config
	{{MASTER_SLAVE_BUS}}_sequencer_config sqr_cfg;
	
	//TLM 
	//default seq_item_port

	//Constructor Function
	function new(string name="{{MODULE}}_{{MASTER_SLAVE_BUS}}_sequencer",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	
	//Phase Methods
	extern virtual function void build_phase(uvm_phase phase);
	extern virtual function void connect_phase(uvm_phase phase);
	extern virtual task run_phase(uvm_phase phase);
	
	{{method}}
	// Add user method here
	//e.g. task function
	// User method ends
endclass

function void {{MODULE}}_{{MASTER_SLAVE_BUS}}_sequencer::build_phase(uvm_phase phase);
	super.build_phase(phase);
	`uvm_info(get_name(),"Build Phase is Called",UVM_LOW)
//	if(!uvm_config_db#({{MASTER_SLAVE_BUS}}_sequencer_config)::get(this,"","sqr_cfg",sqr_cfg))
//	begin
//		`uvm_fatal(get_name(),"Failed Get {{MASTER_SLAVE_BUS}} Sequencer Config")
//	end
	{{build_phase}}	
	// Add user build here
	//e.g. TLM build sqr.set_arbitration()
	// User build ends
endfunction

function void {{MODULE}}_{{MASTER_SLAVE_BUS}}_sequencer::connect_phase(uvm_phase phase);
	super.connect_phase(phase);
	`uvm_info(get_name(),"Connect Phase is Called",UVM_LOW)
	{{connect_phase}}
	// Add user connect here
	//e.g. TLM interface connect
	// User connect ends
endfunction

task {{MODULE}}_{{MASTER_SLAVE_BUS}}_sequencer::run_phase(uvm_phase phase);
	super.run_phase(phase);
	`uvm_info(get_name(),"Run Phase is Called",UVM_LOW)
	{{run_phase}}
	// Add user logic here
	
	// User logic ends
endtask