//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:{{MODULE}}_{{MASTER_SLAVE_BUS}}_sequence_base
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class {{MODULE}}_{{MASTER_SLAVE_BUS}}_sequence_base extends uvm_sequence
{%-if response-%}#({{MASTER_SLAVE_BUS}}_req,{{MASTER_SLAVE_BUS}}_rsp);
{%-else-%}#({{MASTER_SLAVE_BUS}}_req);
{%endif%}
	`uvm_object_utils({{MODULE}}_{{MASTER_SLAVE_BUS}}_sequence_base)
	//Config
	{{MASTER_SLAVE_BUS}}_sequence_config {{MASTER_SLAVE_BUS}}_seq_cfg;
{%if response%}
	//Transaction Sequence item
	{{MASTER_SLAVE_BUS}}_rsp  drv_rsp;
{%endif%}
	//Constructor Function
	function new(string name="{{MODULE}}_{{MASTER_SLAVE_BUS}}_sequence_base");
		super.new(name);
	endfunction
	
	//Task Function Methods
	extern virtual task body();

	{{method}}
	// Add user method here
	//e.g. function
	// User method ends
endclass

task {{MODULE}}_{{MASTER_SLAVE_BUS}}_sequence_base::body();
	{{body}}
	//Add user logic here
	//e.g. `uvm_do_*
	//e.g. `uvm_create()  tr.randomize()  `uvm_send()
	//e.g. create_item()  start_item()   tr.randomize()  finish_item()  get_response()
	// User logic ends
	{%-if response%}
	get_response(drv_rsp);
	{%-endif%}
endtask