//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:sequence_config
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
{%for agt in agt_list%}
class {{agt.name}}_sequence_config extends uvm_object;
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin({{agt.name}}_sequence_config)
	// Add user cfg here
	//e.g. `uvm_field_int
	// User cfg ends
	`uvm_object_utils_end
	function new(string name="{{agt.name}}_sequence_config");
		super.new(name);
	endfunction
endclass
{%endfor%}


class {{MODULE}}_sequence_config extends uvm_object;
{%-for agt in agt_list%}
	{{agt.name}}_sequence_config {{agt.name}}_seq_cfg;
{%-endfor%}
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin({{MODULE}}_sequence_config)
		// Add user cfg here
		//e.g. `uvm_field_int
		// User cfg ends
	`uvm_object_utils_end
	function new(string name="{{MASTER_SLAVE_BUS}}_seq_config");
		super.new(name);
		{%-for agt in agt_list%}
		{{agt.name}}_seq_cfg=new("{{agt.name}}_seq_cfg");
		{%-endfor%}
		// Add user cfg here
	
		// User agent ends	
	endfunction
	{{method}}
	// Add user method here
	//e.g. function
	// User method ends
endclass



