//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_bus_reg_adapter 
//         dut_bus_reg_predictor
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class dut_bus_reg_adapter extends uvm_reg_adapter;

	`uvm_object_utils(dut_bus_reg_adapter)

	//Config
	bus_ral_config reg_adp_cfg;
	
	//default attributes
	//bit provides_responses=0
	//bit supports_byte_enable=0
	
	//Constructor Function
	function new(string name="dut_bus_reg_adapter");
		super.new(name);
		provides_responses=1;
	endfunction
	
	// Methods
	extern virtual function uvm_sequence_item reg2bus(const ref uvm_reg_bus_op rw);
	extern virtual function void bus2reg(uvm_sequence_item bus_item,ref uvm_reg_bus_op rw);	
	
	// Add user method here
	//e.g. task function
	// User method ends
endclass


function uvm_sequence_item dut_bus_reg_adapter::reg2bus(const ref uvm_reg_bus_op rw);
	//Add user logic here
	//e.g. rw.addr,rw.data,rw.kind,rw.b_bits,rw.byte_en,rw.status
	// User logic ends
endfunction
	
function void dut_bus_reg_adapter::bus2reg(uvm_sequence_item bus_item,ref uvm_reg_bus_op rw);
	//Add user logic here
	//e.g. rw.addr,rw.data,rw.kind,rw.b_bits,rw.byte_en,rw.status
	// User logic ends
endfunction

