//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_bus_interface
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
interface dut_bus_inf#(int ADDR_WIDTH=32,int DATA_WIDTH=32)(input logic  PCLK,input logic  PCLKG,input logic  PRESETn);

logic  PSEL;
logic [ADDR_WIDTH<<2-1:2] pAddr;
logic  penable;
logic  PWRite;
logic [DATA_WIDTH-1:0] PWDATA;
logic [31:0] prdata;
logic  pready;
logic  pslverr;


modport dut_bus_dut(
input PCLK,
input PCLKG,
input PRESETn,
input PSEL,
input pAddr,
input penable,
input PWRite,
input PWDATA,
output prdata,
output pready,
output pslverr
);

modport dut_bus_driver(
input  PCLK,
input  PCLKG,
input  PRESETn,
output PSEL,
output pAddr,
output penable,
output PWRite,
output PWDATA,
input prdata,
input pready,
input pslverr
);

modport dut_bus_monitor(
input PCLK,
input PCLKG,
input PRESETn,
input PSEL,
input pAddr,
input penable,
input PWRite,
input PWDATA,
input prdata,
input pready,
input pslverr
);


// Add user logic here
//e.g. assign initial assert
// User logic ends
endinterface