//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_bus
//          _sequencer_config _driver_config _monitor_config 
//          _agent_config _ral_config
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 

 

class bus_sequencer_config extends uvm_object;
	// Add user sequencer cfg here
	
	// User sequencer cfg ends
	`uvm_object_utils_begin(bus_sequencer_config)
	// Add user sequencer cfg here
	//e.g. `uvm_field_int
	// User sequencer cfg ends
	`uvm_object_utils_end
	function new(string name="bus_sequencer_config");
		super.new(name);
	endfunction
endclass



class bus_driver_config extends uvm_object;
	// Add user driver cfg here
	
	// User driver cfg ends
	`uvm_object_utils_begin(bus_driver_config)
	// Add user driver cfg here
	//e.g. `uvm_field_int
	// User driver cfg ends
	`uvm_object_utils_end
	function new(string name="bus_driver_config");
		super.new(name);
	endfunction
endclass



class bus_monitor_config extends uvm_object;
	// Add user monitor cfg here
	
	// User monitor cfg ends
	`uvm_object_utils_begin(bus_monitor_config)
	// Add user monitor cfg here
	//e.g. `uvm_field_int
	// User monitor cfg ends
	`uvm_object_utils_end
	function new(string name="bus_monitor_config");
		super.new(name);
	endfunction
endclass


class bus_agent_config extends uvm_object;
	bus_sequencer_config  sqr_cfg;
	bus_driver_config  drv_cfg;
	bus_monitor_config  moi_cfg;
	uvm_active_passive_enum is_active=UVM_ACTIVE;
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin(bus_agent_config)
		`uvm_field_enum(uvm_active_passive_enum,is_active,UVM_ALL_ON)
		// Add user cfg here
		//e.g. `uvm_field_int
		// User cfg ends
	`uvm_object_utils_end
	function new(string name="bus_agent_config");
		super.new(name);
		sqr_cfg=new("sqr_cfg");
		drv_cfg=new("drv_cfg");
		moi_cfg=new("moi_cfg");
		// Add user cfg here
	
		// User new cfg ends
		
	endfunction
	
	// Add user method here
	//e.g. function
	// User method ends
endclass


class bus_ral_config extends uvm_object;
	bit auto_prediction=1; //default auto perdict
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin(bus_ral_config)
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_end
	function new(string name="bus_ral_config");
		super.new(name);
	endfunction
endclass
