//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:sequence_config
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 

class bus_sequence_config extends uvm_object;
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin(bus_sequence_config)
	// Add user cfg here
	//e.g. `uvm_field_int
	// User cfg ends
	`uvm_object_utils_end
	function new(string name="bus_sequence_config");
		super.new(name);
	endfunction
endclass

class master_sequence_config extends uvm_object;
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin(master_sequence_config)
	// Add user cfg here
	//e.g. `uvm_field_int
	// User cfg ends
	`uvm_object_utils_end
	function new(string name="master_sequence_config");
		super.new(name);
	endfunction
endclass

class slave_sequence_config extends uvm_object;
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin(slave_sequence_config)
	// Add user cfg here
	//e.g. `uvm_field_int
	// User cfg ends
	`uvm_object_utils_end
	function new(string name="slave_sequence_config");
		super.new(name);
	endfunction
endclass



class dut_sequence_config extends uvm_object;
	bus_sequence_config bus_seq_cfg;
	master_sequence_config master_seq_cfg;
	slave_sequence_config slave_seq_cfg;
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin(dut_sequence_config)
		// Add user cfg here
		//e.g. `uvm_field_int
		// User cfg ends
	`uvm_object_utils_end
	function new(string name="slave_seq_config");
		super.new(name);
		bus_seq_cfg=new("bus_seq_cfg");
		master_seq_cfg=new("master_seq_cfg");
		slave_seq_cfg=new("slave_seq_cfg");
		// Add user cfg here
	
		// User agent ends	
	endfunction
	
	// Add user method here
	//e.g. function
	// User method ends
endclass


