//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_virtual_sequencer
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class dut_virtual_sequencer extends uvm_sequencer;
	`uvm_component_utils(dut_virtual_sequencer)
	//Config
	dut_env_config env_cfg;
	
	//Sequencer
	dut_bus_sequencer bus_sqr;
	dut_master_sequencer master_sqr;
	dut_slave_sequencer slave_sqr;

	//Constructor Function
	function new(string name="dut_virtual_sequencer",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	
	
	// Add user method here
	//e.g. task function
	// User method ends
endclass
