//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_harness
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
module tb();

//instance interface);

	dut_bus_inf   bus_inf;

	dut_master_inf   master_inf;

	dut_slave_inf   slave_inf;


//instance dut


initial begin

	uvm_config_db#(virtual dut_bus_inf)::set(null,"uvm_test_top.env.bus_agt","bus_inf",bus_inf);

	uvm_config_db#(virtual dut_master_inf)::set(null,"uvm_test_top.env.master_agt","master_inf",master_inf);

	uvm_config_db#(virtual dut_slave_inf)::set(null,"uvm_test_top.env.slave_agt","slave_inf",slave_inf);

end

initial
begin
	`ifdef DUMP_FSDB
		$fsdbDumpfile("simv.fsdb");
		$fsdbDumpvars(0,tb);
	`endif
	`ifdef DUMP_VPD
		$vcdpluson();
	`endif
end

initial
begin
	$display("-------------------------------------------------------");
	$display("------------------------Start--------------------------");
	$display("-------------------------------------------------------");
	run_test();
	$display("-------------------------------------------------------");
	$display("-----------------------Finish--------------------------");
	$display("-------------------------------------------------------");
end

// Add user logic here

// User logic ends
endmodule