//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_env_config dut_callback
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class dut_env_config extends uvm_object;
	// Add user cfg here
	
	// User cfg ends
	`uvm_object_utils_begin(dut_env_config)
	// Add user cfg here
	//e.g. `uvm_field_int
	// User cfg ends
	`uvm_object_utils_end
	function new(string name="dut_config");
		super.new(name);
	endfunction
endclass

class dut_callback extends uvm_callback;
	`uvm_object_utils(dut_callback)
	
	//Constructor Function
	function new(string name="dut_callback");
		super.new(name);
	endfunction
	
	// Add user method here

	// User method ends	
endclass 