//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//File:dut_harness.sv
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
module tb();
reg PCLK;
reg PCLKG;
reg PRESETn;
dut_bus_inf   bus_inf(PCLK,PCLKG,PRESETn);

dut_master_inf   master_inf(PCLK,PCLKG,PRESETn);

dut_slave_inf   slave_inf(PCLK,PCLKG,PRESETn);


//instance dut
dut u_dut(
.PClk(PCLK),
.PCLKG(PCLKG),
.PRESETn(PRESETn),
.PSEL(bus_inf.PSEL),
.pAddr(bus_inf.pAddr),
.penable(bus_inf.penable),
.PWRite(bus_inf.PWRite),
.PWDATA(bus_inf.PWDATA),
.prdata(bus_inf.prdata),
.pready(bus_inf.pready),
.pslverr(bus_inf.pslverr),

//master side
.RXD(master_inf.RXD),
.data_st(master_inf.data_st),
.addr_st(master_inf.addr_st),
.control(master_inf.control),
.request(master_inf.request),
.valid(master_inf.valid),
.data_ld(master_inf.data_ld),
.addr_ld(master_inf.addr_ld),

//slave side
.TXD(slave_inf.TXD),
.data_wrt(slave_inf.data_wrt),
.addr_wrt(slave_inf.addr_wrt),
.regrant(slave_inf.regrant),
.confirm(slave_inf.confirm),
.data_rd(slave_inf.data_rd),
.addr_rd(slave_inf.addr_rd)
);

initial begin

	uvm_config_db#(virtual dut_bus_inf)::set(null,"uvm_test_top.env.bus_agt","bus_inf",bus_inf);

	uvm_config_db#(virtual dut_master_inf)::set(null,"uvm_test_top.env.master_agt","master_inf",master_inf);

	uvm_config_db#(virtual dut_slave_inf)::set(null,"uvm_test_top.env.slave_agt","slave_inf",slave_inf);

end





initial
begin
	`ifdef DUMP_FSDB
		$fsdbDumpfile("simv.fsdb");
		$fsdbDumpvars(0,tb);
	`endif
	`ifdef DUMP_VPD
		$vcdpluson();
	`endif
end

initial
begin
	$display("-------------------------------------------------------");
	$display("------------------------Start--------------------------");
	$display("-------------------------------------------------------");
	run_test();
end

// Add user logic here

// User logic ends
endmodule