//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_master_agent
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class dut_master_agent extends uvm_agent;

	`uvm_component_utils(dut_master_agent)

	//Config	//Interface
	master_agent_config agt_cfg;
	virtual dut_master_inf master_inf;
	
	//TLM 
	uvm_analysis_port#(master_req) moi_port;
	
	//Components
	dut_master_sequencer master_sqr;
	dut_master_driver master_drv;
	dut_master_monitor master_moi;
	
	//Constructor Function
	function new(string name="dut_master_agent",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	
	//Phase Methods
	extern virtual function void build_phase(uvm_phase phase);
	extern virtual function void connect_phase(uvm_phase phase);
	extern virtual task run_phase(uvm_phase phase);
	
	
	// Add user method here
	//e.g. task function
	// User method ends
endclass

function void dut_master_agent::build_phase(uvm_phase phase);
	super.build_phase(phase);
	`uvm_info(get_name(),"Build Phase is Called",UVM_LOW)
	if(!uvm_config_db#(master_agent_config)::get(this,"","agt_cfg",agt_cfg))
	begin
		`uvm_fatal(get_name(),"Failed Get {MASTER_SLAVE_BUS}} Agent Config")
	end
	if(!uvm_config_db#(virtual dut_master_inf)::get(this,"","master_inf",master_inf))
	begin
		`uvm_fatal(get_name(),"Failed Get Virtual Interfac dut_master_inf")
	end
	master_moi=dut_master_monitor::type_id::create("master_moi",this);
	master_moi.moi_cfg=agt_cfg.moi_cfg;
	if (agt_cfg.is_active==UVM_ACTIVE)
	begin
		master_sqr=dut_master_sequencer::type_id::create("master_sqr",this);
		master_sqr.sqr_cfg=agt_cfg.sqr_cfg;
		master_drv=dut_master_driver::type_id::create("master_drv",this);
		master_drv.drv_cfg=agt_cfg.drv_cfg;
	end
	
	// Add user build here
	//e.g. TLM build
	// User build ends
endfunction

function void dut_master_agent::connect_phase(uvm_phase phase);
	super.connect_phase(phase);
	`uvm_info(get_name(),"Connect Phase is Called",UVM_LOW)
	master_moi.master_inf=master_inf;
	moi_port=master_moi.moi_port;
	if (agt_cfg.is_active==UVM_ACTIVE)
	begin
		master_drv.master_inf=master_inf;
		
		master_drv.seq_item_port.connect(master_sqr.seq_item_export);
	end
	
	// Add user connect here
	//e.g. TLM  interface connect
	// User connect ends
endfunction

task dut_master_agent::run_phase(uvm_phase phase);
	super.run_phase(phase);
	`uvm_info(get_name(),"Run Phase is Called",UVM_LOW)
	
	// Add user logic here

	// User logic ends
endtask



	
	
	