//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_master_sequence_base
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class dut_master_sequence_base extends uvm_sequence#(master_req,master_rsp);
	`uvm_object_utils(dut_master_sequence_base)
	//Config
	master_sequence_config master_seq_cfg;

	//Transaction Sequence item
	master_rsp  drv_rsp;

	//Constructor Function
	function new(string name="dut_master_sequence_base");
		super.new(name);
	endfunction
	
	//Task Function Methods
	extern virtual task body();

	
	// Add user method here
	//e.g. function
	// User method ends
endclass

task dut_master_sequence_base::body();
	
	//Add user logic here
	//e.g. `uvm_do_*
	//e.g. `uvm_create()  tr.randomize()  `uvm_send()
	//e.g. create_item()  start_item()   tr.randomize()  finish_item()  get_response()
	// User logic ends
	get_response(drv_rsp);
endtask