//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_master_interface
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
interface dut_master_inf#()(input logic  PCLK,input logic  PCLKG,input logic  PRESETn);

logic  RXD;
logic [31:0] data_st;
logic [31:0] addr_st;
logic [7:0] control;
logic  request;
logic [2:0] valid;
logic [31:0] data_ld;
logic [31:0] addr_ld;


modport dut_master_dut(
input PCLK,
input PCLKG,
input PRESETn,
input RXD,
input data_st,
input addr_st,
input control,
output request,
output valid,
output data_ld,
output addr_ld
);

modport dut_master_driver(
input  PCLK,
input  PCLKG,
input  PRESETn,
output RXD,
output data_st,
output addr_st,
output control,
input request,
input valid,
input data_ld,
input addr_ld
);

modport dut_master_monitor(
input PCLK,
input PCLKG,
input PRESETn,
input RXD,
input data_st,
input addr_st,
input control,
input request,
input valid,
input data_ld,
input addr_ld
);


// Add user logic here
//e.g. assign initial assert
// User logic ends
endinterface