//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_slave_agent
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class dut_slave_agent extends uvm_agent;

	`uvm_component_utils(dut_slave_agent)

	//Config	//Interface
	slave_agent_config agt_cfg;
	virtual dut_slave_inf slave_inf;
	
	//TLM 
	uvm_analysis_port#(slave_req) moi_port;
	
	//Components
	dut_slave_sequencer slave_sqr;
	dut_slave_driver slave_drv;
	dut_slave_monitor slave_moi;
	
	//Constructor Function
	function new(string name="dut_slave_agent",uvm_component parent=null);
		super.new(name,parent);
	endfunction
	
	//Phase Methods
	extern virtual function void build_phase(uvm_phase phase);
	extern virtual function void connect_phase(uvm_phase phase);
	extern virtual task run_phase(uvm_phase phase);
	
	
	// Add user method here
	//e.g. task function
	// User method ends
endclass

function void dut_slave_agent::build_phase(uvm_phase phase);
	super.build_phase(phase);
	`uvm_info(get_name(),"Build Phase is Called",UVM_LOW)
	if(!uvm_config_db#(slave_agent_config)::get(this,"","agt_cfg",agt_cfg))
	begin
		`uvm_fatal(get_name(),"Failed Get {MASTER_SLAVE_BUS}} Agent Config")
	end
	if(!uvm_config_db#(virtual dut_slave_inf)::get(this,"","slave_inf",slave_inf))
	begin
		`uvm_fatal(get_name(),"Failed Get Virtual Interfac dut_slave_inf")
	end
	slave_moi=dut_slave_monitor::type_id::create("slave_moi",this);
	slave_moi.moi_cfg=agt_cfg.moi_cfg;
	if (agt_cfg.is_active==UVM_ACTIVE)
	begin
		slave_sqr=dut_slave_sequencer::type_id::create("slave_sqr",this);
		slave_sqr.sqr_cfg=agt_cfg.sqr_cfg;
		slave_drv=dut_slave_driver::type_id::create("slave_drv",this);
		slave_drv.drv_cfg=agt_cfg.drv_cfg;
	end
	
	// Add user build here
	//e.g. TLM build
	// User build ends
endfunction

function void dut_slave_agent::connect_phase(uvm_phase phase);
	super.connect_phase(phase);
	`uvm_info(get_name(),"Connect Phase is Called",UVM_LOW)
	slave_moi.slave_inf=slave_inf;
	moi_port=slave_moi.moi_port;
	if (agt_cfg.is_active==UVM_ACTIVE)
	begin
		slave_drv.slave_inf=slave_inf;
		
		slave_drv.seq_item_port.connect(slave_sqr.seq_item_export);
	end
	
	// Add user connect here
	//e.g. TLM  interface connect
	// User connect ends
endfunction

task dut_slave_agent::run_phase(uvm_phase phase);
	super.run_phase(phase);
	`uvm_info(get_name(),"Run Phase is Called",UVM_LOW)
	
	// Add user logic here

	// User logic ends
endtask



	
	
	