//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_slave_sequence_base
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
class dut_slave_sequence_base extends uvm_sequence#(slave_req);

	`uvm_object_utils(dut_slave_sequence_base)
	//Config
	slave_sequence_config slave_seq_cfg;

	//Constructor Function
	function new(string name="dut_slave_sequence_base");
		super.new(name);
	endfunction
	
	//Task Function Methods
	extern virtual task body();

	
	// Add user method here
	//e.g. function
	// User method ends
endclass

task dut_slave_sequence_base::body();
	
	//Add user logic here
	//e.g. `uvm_do_*
	//e.g. `uvm_create()  tr.randomize()  `uvm_send()
	//e.g. create_item()  start_item()   tr.randomize()  finish_item()  get_response()
	// User logic ends
endtask