//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_slave_tranaction(request & response)
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 

 


class slave_req extends uvm_sequence_item;
	// Add user data here
	//e.g. rand int addr
	// User data ends
	`uvm_object_utils_begin(slave_req)
	// Add user data here
	//e.g. `uvm_field_int
	// User data ends
	`uvm_object_utils_end
	function new(string name="slave_req");
		super.new(name);
	endfunction
	
	// Add user method here
	//e.g. implement constarins
	// User method ends	
endclass





