//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
//Auto Generated by UVM-Generator
//Author: Jiacai Yuan
//E-mail: yuan861025184@163.com
//Contents:dut_slave_interface
//***** ***** ***** *****  *****  *****  *****  *****  *****  *****  ***** 
interface dut_slave_inf#(int ADDR_WIDTH=32,int DATA_WIDTH=32)();

logic  TXD;
logic [7:0] data_wrt;
logic [7:0] addr_wrt;
logic  regrant;
logic [3:0] confirm;
logic [7:0] data_rd;
logic [7:0] addr_rd;


modport dut_slave_dut(
output TXD,
output data_wrt,
output addr_wrt,
output regrant,
input confirm,
input data_rd,
input addr_rd
);

modport dut_slave_driver(
input TXD,
input data_wrt,
input addr_wrt,
input regrant,
output confirm,
output data_rd,
output addr_rd
);

modport dut_slave_monitor(
input TXD,
input data_wrt,
input addr_wrt,
input regrant,
input confirm,
input data_rd,
input addr_rd
);


// Add user logic here
//e.g. assign initial assert
// User logic ends
endinterface