//
// Note:
// This file is generated by Mako Template
//-----------------------------------------
// ${agent_name} agent configuration
//
class ${agent_name}_agent_cfg extends uvm_object;
  `uvm_object_utils(${agent_name}_agent_cfg)

  bit ACTIVE = 1;

  % for i in itf:
  virtual ${i}_if ${i}_vif;
  % endfor  

  function new(string name = "${agent_name}_agent_cfg");
    super.new(name);
  endfunction // new
  
  
endclass // ${agent_name}_agent_cfg
